server:
  port: 8888

spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
  sleuth:
    annotation:
      enabled: true

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
      leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

management:
  security:
    enabled: false
  health:
    defaults: true
    sensitive: true
  endpoints:
    web:
      expose: "*"
    health:
      show-details: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST 

zuul:
  routes:
    subjects:
      path: /api/subjects/**
      sensitiveHeaders: 
      serviceId: subjects
    teachers:
      path: /api/teachers/**
      sensitiveHeaders:
      serviceId: teachers
  
  host:
    connectTimeoutMillis: 3000
    socketTimeoutMillis: 3000
proxy:
   auth:
     routes:
       subjects: oauth2
       teachers: oauth2
