server:
  port: 40005
spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
  sleuth:
    annotation:
      enabled: true
  data:
    mongodb:
      database: teachers
      host: 192.168.99.100 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

subjects:
  service: SUBJECTS

