turbine:
  stream:
    port: 8010
  appConfig: subjects,teachers
  clusterNameExpression: 'default'

spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
