server:
  port: 7777
  servlet:
    context-path: oauth
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/core
    username: root
    password: ropandi1234
    validationQuery: SELECT 1
    tomcat:
     max-wait: 20000
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 600000
      maximumPoolSize: 3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        id:
         new_generator_mappings: false
        format_sql: true
  cloud:
    discovery:
     enabled: false        
#custom
jwt:
  keySecret: SewrtnjlbadaydywttgaggGGRRRghashsbshhsgfgrRRRTATgahahbBKKAJANnhyattara545637abgBbBBNAvgagyt
  accessToken:
     expirationInMiliseconds: 60000
  refreshToken:
     expirationInMiliseconds: 3600000
  
    
  
